#!/usr/bin/env python
# adminInterface.py

import cPickle as pickle
import wx, os

# ~+-~+-~+-~+-~+-~+-~+-~+-~+-~+-~+-~+-~+-~+-~+-~+-~+-~+-~+-~+-~+-~+-~+-~+-~+-~+-~+-~+-~+-~
# ~+-~+-~+-~+-~+-~+-~+-~+-~+-~+-~+-~+-~+-~+-~+-~+-~+-~+-~+-~+-~+-~+-~+-~+-~+-~+-~+-~+-~+-~
class MyDialog(wx.Dialog):
    def __init__(self, *args, **kwds):
        kwds["style"] = wx.DEFAULT_DIALOG_STYLE
        wx.Dialog.__init__(self, *args, **kwds)
        self.notebook_1 = wx.Notebook(self, -1, style=0)
        self.notebook_1_pane_1 = wx.Panel(self.notebook_1, -1)
        self.label_1 = wx.StaticText(self.notebook_1_pane_1, -1, "Player Name: ")
        self.playerNameBox = wx.TextCtrl(self.notebook_1_pane_1, -1, "")
        self.label_2 = wx.StaticText(self.notebook_1_pane_1, -1, "Player ID #: ")
        self.playerIDBox = wx.TextCtrl(self.notebook_1_pane_1, -1, "")
        self.label_3 = wx.StaticText(self.notebook_1_pane_1, -1, "Player Handle: ")
        self.playerHandleBox = wx.TextCtrl(self.notebook_1_pane_1, -1, "")
        self.label_4 = wx.StaticText(self.notebook_1_pane_1, -1, "Right or Left Handed?: ")
        self.playerHandBox = wx.ComboBox(self.notebook_1_pane_1, -1, choices=["Left Hand", "Right Hand"], style=wx.CB_DROPDOWN)
        self.label_5 = wx.StaticText(self.notebook_1_pane_1, -1, "Flexor Placement: ")
        self.playerFlexorBox = wx.ComboBox(self.notebook_1_pane_1, -1, choices=["[Default] Arm Flexor (Underside)"], style=wx.CB_DROPDOWN)
        self.label_6 = wx.StaticText(self.notebook_1_pane_1, -1, "Extensor Placement: ")
        self.playerExtensorBox = wx.ComboBox(self.notebook_1_pane_1, -1, choices=["[Default] Arm Extensor (Top)"], style=wx.CB_DROPDOWN)
        self.panel_10 = wx.Panel(self.notebook_1_pane_1, -1)
        self.panel_12 = wx.Panel(self.notebook_1_pane_1, -1)
        self.panel_11 = wx.Panel(self.notebook_1_pane_1, -1)
        self.panel_13 = wx.Panel(self.notebook_1_pane_1, -1)
        self.notebook_1_pane_2 = wx.Panel(self.notebook_1, -1)
        self.label_24 = wx.StaticText(self.notebook_1_pane_2, -1, "Server Address: ")
        self.serverAddressBox = wx.TextCtrl(self.notebook_1_pane_2, -1, "")
        self.label_25 = wx.StaticText(self.notebook_1_pane_2, -1, "Server Directory: ")
        self.serverDirectoryBox = wx.TextCtrl(self.notebook_1_pane_2, -1, "")
        self.label_26 = wx.StaticText(self.notebook_1_pane_2, -1, "serverLogin: ")
        self.serverserverLoginBox = wx.TextCtrl(self.notebook_1_pane_2, -1, "")
        self.label_27 = wx.StaticText(self.notebook_1_pane_2, -1, "Passkey: ")
        self.serverPasskeyBox = wx.TextCtrl(self.notebook_1_pane_2, -1, "")
        self.panel_2 = wx.Panel(self.notebook_1_pane_2, -1)
        self.panel_3 = wx.Panel(self.notebook_1_pane_2, -1)
        self.panel_4 = wx.Panel(self.notebook_1_pane_2, -1)
        self.panel_7 = wx.Panel(self.notebook_1_pane_2, -1)
        self.panel_5 = wx.Panel(self.notebook_1_pane_2, -1)
        self.panel_8 = wx.Panel(self.notebook_1_pane_2, -1)
        self.panel_6 = wx.Panel(self.notebook_1_pane_2, -1)
        self.panel_9 = wx.Panel(self.notebook_1_pane_2, -1)
        self.notebook_1_pane_3 = wx.Panel(self.notebook_1, -1)
        self.label_18 = wx.StaticText(self.notebook_1_pane_3, -1, "Channel 1 Gain: ")
        self.ch1GainBox = wx.TextCtrl(self.notebook_1_pane_3, -1, "5.0")
        self.label_20 = wx.StaticText(self.notebook_1_pane_3, -1, "Channel 2 Gain: ")
        self.ch2GainBox = wx.TextCtrl(self.notebook_1_pane_3, -1, "5.0")
        self.label_19 = wx.StaticText(self.notebook_1_pane_3, -1, "Channel 1 Offset: ")
        self.ch1OffsetBox = wx.TextCtrl(self.notebook_1_pane_3, -1, "0.0")
        self.label_21 = wx.StaticText(self.notebook_1_pane_3, -1, "Channel 2 Offset: ")
        self.ch2OffsetBox = wx.TextCtrl(self.notebook_1_pane_3, -1, "0.0")
        self.label_11 = wx.StaticText(self.notebook_1_pane_3, -1, "EMG 2 Mouse Gain:")
        self.emg2mouseGainBox = wx.TextCtrl(self.notebook_1_pane_3, -1, "2.5")
        self.label_12 = wx.StaticText(self.notebook_1_pane_3, -1, "EMG 2 Mouse Slope: ")
        self.emg2MouseSlopeBox = wx.TextCtrl(self.notebook_1_pane_3, -1, "1.6")
        self.label_14 = wx.StaticText(self.notebook_1_pane_3, -1, "EMG 2 Mouse X Offset: ")
        self.emg2MouseOffsetBox = wx.TextCtrl(self.notebook_1_pane_3, -1, "")
        self.label_15 = wx.StaticText(self.notebook_1_pane_3, -1, "Smoother Num Medians: ")
        self.mediansBox = wx.TextCtrl(self.notebook_1_pane_3, -1, "")
        self.label_16 = wx.StaticText(self.notebook_1_pane_3, -1, "EMG Buffer Minimum Samples: ")
        self.minSamplesBox = wx.TextCtrl(self.notebook_1_pane_3, -1, "")
        self.label_17 = wx.StaticText(self.notebook_1_pane_3, -1, "Output Sample Rate: ")
        self.sampleRateBox = wx.TextCtrl(self.notebook_1_pane_3, -1, "")
        self.serialParityBox = wx.Panel(self.notebook_1, -1)
        self.label_28 = wx.StaticText(self.serialParityBox, -1, "Port: ")
        self.serialPortBox = wx.ComboBox(self.serialParityBox, -1, choices=["COM1", "COM2", "COM3", "COM4", "COM5", "COM6"], style=wx.CB_DROPDOWN)
        self.label_29 = wx.StaticText(self.serialParityBox, -1, "Baudrate: ")
        self.serialBaudBox = wx.ComboBox(self.serialParityBox, -1, choices=["19200", "38400", "57600", "115200"], style=wx.CB_DROPDOWN)
        self.label_30 = wx.StaticText(self.serialParityBox, -1, "Data Bits: ")
        self.serialDataBitsBox = wx.ComboBox(self.serialParityBox, -1, choices=["5", "6", "7", "8"], style=wx.CB_DROPDOWN)
        self.label_31 = wx.StaticText(self.serialParityBox, -1, "Stop Bits: ")
        self.serialStopBitsBox = wx.ComboBox(self.serialParityBox, -1, choices=["1", "1.5", "2"], style=wx.CB_DROPDOWN)
        self.label_32 = wx.StaticText(self.serialParityBox, -1, "Parity: ")
        self.combo_box_8 = wx.ComboBox(self.serialParityBox, -1, choices=["None", "Even", "Odd", "Mark", "Space"], style=wx.CB_DROPDOWN)
        self.label_33 = wx.StaticText(self.serialParityBox, -1, "Flow Control: ")
        self.serialRTSCheck = wx.CheckBox(self.serialParityBox, -1, "RTS/CTS ")
        self.serialXonCheck = wx.CheckBox(self.serialParityBox, -1, "Xon/Xoff ")
        self.panel_14 = wx.Panel(self.serialParityBox, -1)
        self.panel_16 = wx.Panel(self.serialParityBox, -1)
        self.panel_15 = wx.Panel(self.serialParityBox, -1)
        self.panel_17 = wx.Panel(self.serialParityBox, -1)
        self.button_1 = wx.Button(self, wx.ID_OK, "")
        self.button_2 = wx.Button(self, wx.ID_CANCEL, "")

        self.__set_properties()
        self.__do_layout()
        self.Bind(wx.EVT_BUTTON, self.OnOK, self.button_1)
        self.Bind(wx.EVT_BUTTON, self.OnCancel, self.button_2)

        self.serverHost = 'HOSTNAME'
        self.serverDir = 'SERVERDIR'
        self.serverLogin = 'LOGIN'
        self.password = 'PASSWORD'
        self.playername = 'Neurogame Player'
        self.playerID = '99'
        self.playerhandle = 'Player_99'
        self.playerside = 'Right Hand'
        self.playerflexor = '[Default] Arm Flexor (Underside)'
        self.playerextensor = '[Default] Arm Extensor (Top)'
        self.numberMVCs = '3'
        self.rightward = 'right'
        self.leftward = 'left'
        self.changain = [5,5]
        self.chanoffset = [0,0]
        self.gainEMG = 2.5
        self.slopeEMG = 2.0
        self.EMGxoffset = 20
        self.smoothernummeds = 7
        self.EMGnumSamples = 1
        self.serialSampleRate = 1000
        self.DefineVariables()

# ~+-~+-~+-~+-~+-~+-~+-~+-~+-~+-~+-~+-~+-~+-~+-~+-~+-~+-~+-~+-~+-~+-~+-~+-~+-~+-~+-~+-~+-~
# ~+-~+-~+-~+-~+-~+-~+-~+-~+-~+-~+-~+-~+-~+-~+-~+-~+-~+-~+-~+-~+-~+-~+-~+-~+-~+-~+-~+-~+-~
    def __set_properties(self):
        self.SetTitle("NeuroGame Configuration")
        self.SetSize(wx.DLG_SZE(self, (359, 269)))
        self.label_1.SetFont(wx.Font(12, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, ""))
        self.playerNameBox.SetMinSize((200, 20))
        self.label_2.SetFont(wx.Font(12, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, ""))
        self.playerIDBox.SetMinSize((200, 20))
        self.label_3.SetFont(wx.Font(12, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, ""))
        self.playerHandleBox.SetMinSize((200, 20))
        self.label_4.SetFont(wx.Font(12, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, ""))
        self.playerHandBox.SetMinSize((200, 21))
        self.playerHandBox.SetSelection(1)
        self.label_5.SetFont(wx.Font(12, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, ""))
        self.playerFlexorBox.SetMinSize((200, 21))
        self.playerFlexorBox.SetSelection(0)
        self.label_6.SetFont(wx.Font(12, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, ""))
        self.playerExtensorBox.SetMinSize((200, 21))
        self.playerExtensorBox.SetSelection(0)
        self.label_24.SetFont(wx.Font(12, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, ""))
        self.serverAddressBox.SetMinSize((200, 20))
        self.label_25.SetFont(wx.Font(12, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, ""))
        self.serverDirectoryBox.SetMinSize((200, 20))
        self.label_26.SetFont(wx.Font(12, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, ""))
        self.serverserverLoginBox.SetMinSize((200, 20))
        self.label_27.SetFont(wx.Font(12, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, ""))
        self.serverPasskeyBox.SetMinSize((200, 20))
        self.label_18.SetFont(wx.Font(12, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, ""))
        self.ch1GainBox.SetMinSize((84, 20))
        self.label_20.SetFont(wx.Font(12, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, ""))
        self.ch2GainBox.SetMinSize((84, 20))
        self.label_19.SetFont(wx.Font(12, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, ""))
        self.ch1OffsetBox.SetMinSize((84, 20))
        self.label_21.SetFont(wx.Font(12, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, ""))
        self.ch2OffsetBox.SetMinSize((84, 20))
        self.label_11.SetFont(wx.Font(12, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, ""))
        self.emg2mouseGainBox.SetMinSize((200, 20))
        self.label_12.SetFont(wx.Font(12, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, ""))
        self.emg2MouseSlopeBox.SetMinSize((200, 20))
        self.label_14.SetFont(wx.Font(12, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, ""))
        self.emg2MouseOffsetBox.SetMinSize((200, 20))
        self.label_15.SetFont(wx.Font(12, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, ""))
        self.mediansBox.SetMinSize((200, 20))
        self.label_16.SetFont(wx.Font(12, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, ""))
        self.minSamplesBox.SetMinSize((200, 20))
        self.label_17.SetFont(wx.Font(12, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, ""))
        self.sampleRateBox.SetMinSize((200, 20))
        self.label_28.SetFont(wx.Font(12, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, ""))
        self.serialPortBox.SetMinSize((200, 21))
        self.serialPortBox.SetSelection(0)
        self.label_29.SetFont(wx.Font(12, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, ""))
        self.serialBaudBox.SetMinSize((200, 21))
        self.serialBaudBox.SetSelection(2)
        self.label_30.SetFont(wx.Font(12, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, ""))
        self.serialDataBitsBox.SetMinSize((200, 21))
        self.serialDataBitsBox.SetSelection(3)
        self.label_31.SetFont(wx.Font(12, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, ""))
        self.serialStopBitsBox.SetMinSize((200, 21))
        self.serialStopBitsBox.SetSelection(0)
        self.label_32.SetFont(wx.Font(12, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, ""))
        self.combo_box_8.SetMinSize((200, 21))
        self.combo_box_8.SetSelection(0)
        self.label_33.SetFont(wx.Font(12, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, ""))
        self.serialRTSCheck.SetFont(wx.Font(12, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, ""))
        self.serialXonCheck.SetFont(wx.Font(12, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, ""))

# ~+-~+-~+-~+-~+-~+-~+-~+-~+-~+-~+-~+-~+-~+-~+-~+-~+-~+-~+-~+-~+-~+-~+-~+-~+-~+-~+-~+-~+-~
# ~+-~+-~+-~+-~+-~+-~+-~+-~+-~+-~+-~+-~+-~+-~+-~+-~+-~+-~+-~+-~+-~+-~+-~+-~+-~+-~+-~+-~+-~
    def __do_layout(self):
        sizer_1 = wx.BoxSizer(wx.VERTICAL)
        sizer_2 = wx.BoxSizer(wx.HORIZONTAL)
        grid_sizer_8 = wx.GridSizer(8, 2, 0, 0)
        sizer_7 = wx.BoxSizer(wx.HORIZONTAL)
        grid_sizer_2 = wx.GridSizer(8, 2, 0, 0)
        grid_sizer_6 = wx.GridSizer(1, 2, 0, 0)
        grid_sizer_4 = wx.GridSizer(1, 2, 0, 0)
        grid_sizer_5 = wx.GridSizer(1, 2, 0, 0)
        grid_sizer_3 = wx.GridSizer(1, 2, 0, 0)
        grid_sizer_7 = wx.GridSizer(8, 2, 0, 0)
        grid_sizer_1 = wx.GridSizer(8, 2, 0, 0)
        grid_sizer_1.Add(self.label_1, 0, wx.LEFT | wx.RIGHT | wx.TOP | wx.ALIGN_CENTER_VERTICAL, 15)
        grid_sizer_1.Add(self.playerNameBox, 0, wx.LEFT | wx.RIGHT | wx.TOP | wx.ALIGN_RIGHT | wx.ALIGN_CENTER_VERTICAL, 15)
        grid_sizer_1.Add(self.label_2, 0, wx.LEFT | wx.RIGHT | wx.TOP | wx.ALIGN_CENTER_VERTICAL, 15)
        grid_sizer_1.Add(self.playerIDBox, 0, wx.LEFT | wx.RIGHT | wx.TOP | wx.ALIGN_RIGHT | wx.ALIGN_CENTER_VERTICAL, 15)
        grid_sizer_1.Add(self.label_3, 0, wx.LEFT | wx.RIGHT | wx.TOP | wx.ALIGN_CENTER_VERTICAL, 15)
        grid_sizer_1.Add(self.playerHandleBox, 0, wx.LEFT | wx.RIGHT | wx.TOP | wx.ALIGN_RIGHT | wx.ALIGN_CENTER_VERTICAL, 15)
        grid_sizer_1.Add(self.label_4, 0, wx.LEFT | wx.RIGHT | wx.TOP | wx.ALIGN_CENTER_VERTICAL, 15)
        grid_sizer_1.Add(self.playerHandBox, 0, wx.LEFT | wx.RIGHT | wx.TOP | wx.ALIGN_RIGHT | wx.ALIGN_CENTER_VERTICAL, 15)
        grid_sizer_1.Add(self.label_5, 0, wx.LEFT | wx.RIGHT | wx.TOP | wx.ALIGN_CENTER_VERTICAL, 15)
        grid_sizer_1.Add(self.playerFlexorBox, 0, wx.LEFT | wx.RIGHT | wx.TOP | wx.ALIGN_RIGHT | wx.ALIGN_CENTER_VERTICAL, 15)
        grid_sizer_1.Add(self.label_6, 0, wx.LEFT | wx.RIGHT | wx.TOP | wx.ALIGN_CENTER_VERTICAL, 15)
        grid_sizer_1.Add(self.playerExtensorBox, 0, wx.LEFT | wx.RIGHT | wx.TOP | wx.ALIGN_RIGHT | wx.ALIGN_CENTER_VERTICAL, 15)
        grid_sizer_1.Add(self.panel_10, 1, wx.EXPAND, 0)
        grid_sizer_1.Add(self.panel_12, 1, wx.EXPAND, 0)
        grid_sizer_1.Add(self.panel_11, 1, wx.EXPAND, 0)
        grid_sizer_1.Add(self.panel_13, 1, wx.EXPAND, 0)
        self.notebook_1_pane_1.SetSizer(grid_sizer_1)
        grid_sizer_7.Add(self.label_24, 0, wx.LEFT | wx.RIGHT | wx.TOP | wx.ALIGN_CENTER_VERTICAL, 15)
        grid_sizer_7.Add(self.serverAddressBox, 0, wx.LEFT | wx.RIGHT | wx.TOP | wx.ALIGN_RIGHT | wx.ALIGN_CENTER_VERTICAL, 15)
        grid_sizer_7.Add(self.label_25, 0, wx.LEFT | wx.RIGHT | wx.TOP | wx.ALIGN_CENTER_VERTICAL, 15)
        grid_sizer_7.Add(self.serverDirectoryBox, 0, wx.LEFT | wx.RIGHT | wx.TOP | wx.ALIGN_RIGHT | wx.ALIGN_CENTER_VERTICAL, 15)
        grid_sizer_7.Add(self.label_26, 0, wx.LEFT | wx.RIGHT | wx.TOP | wx.ALIGN_CENTER_VERTICAL, 15)
        grid_sizer_7.Add(self.serverserverLoginBox, 0, wx.LEFT | wx.RIGHT | wx.TOP | wx.ALIGN_RIGHT | wx.ALIGN_CENTER_VERTICAL, 15)
        grid_sizer_7.Add(self.label_27, 0, wx.LEFT | wx.RIGHT | wx.TOP | wx.ALIGN_CENTER_VERTICAL, 15)
        grid_sizer_7.Add(self.serverPasskeyBox, 0, wx.LEFT | wx.RIGHT | wx.TOP | wx.ALIGN_RIGHT | wx.ALIGN_CENTER_VERTICAL, 15)
        grid_sizer_7.Add(self.panel_2, 1, wx.EXPAND, 0)
        grid_sizer_7.Add(self.panel_3, 1, wx.EXPAND, 0)
        grid_sizer_7.Add(self.panel_4, 1, wx.EXPAND, 0)
        grid_sizer_7.Add(self.panel_7, 1, wx.EXPAND, 0)
        grid_sizer_7.Add(self.panel_5, 1, wx.EXPAND, 0)
        grid_sizer_7.Add(self.panel_8, 1, wx.EXPAND, 0)
        grid_sizer_7.Add(self.panel_6, 1, wx.EXPAND, 0)
        grid_sizer_7.Add(self.panel_9, 1, wx.EXPAND, 0)
        self.notebook_1_pane_2.SetSizer(grid_sizer_7)
        grid_sizer_3.Add(self.label_18, 0, wx.LEFT | wx.TOP | wx.ALIGN_CENTER_VERTICAL, 15)
        grid_sizer_3.Add(self.ch1GainBox, 0, wx.LEFT | wx.RIGHT | wx.TOP | wx.ALIGN_RIGHT | wx.ALIGN_CENTER_VERTICAL, 15)
        grid_sizer_2.Add(grid_sizer_3, 0, wx.EXPAND, 0)
        grid_sizer_5.Add(self.label_20, 0, wx.TOP | wx.ALIGN_CENTER_VERTICAL, 15)
        grid_sizer_5.Add(self.ch2GainBox, 0, wx.RIGHT | wx.TOP | wx.ALIGN_RIGHT | wx.ALIGN_CENTER_VERTICAL, 15)
        grid_sizer_2.Add(grid_sizer_5, 0, wx.EXPAND, 0)
        grid_sizer_4.Add(self.label_19, 0, wx.LEFT | wx.TOP | wx.ALIGN_CENTER_VERTICAL, 15)
        grid_sizer_4.Add(self.ch1OffsetBox, 0, wx.LEFT | wx.RIGHT | wx.TOP | wx.ALIGN_RIGHT | wx.ALIGN_CENTER_VERTICAL, 15)
        grid_sizer_2.Add(grid_sizer_4, 0, wx.EXPAND, 0)
        grid_sizer_6.Add(self.label_21, 0, wx.TOP | wx.ALIGN_CENTER_VERTICAL, 15)
        grid_sizer_6.Add(self.ch2OffsetBox, 0, wx.RIGHT | wx.TOP | wx.ALIGN_RIGHT | wx.ALIGN_CENTER_VERTICAL, 15)
        grid_sizer_2.Add(grid_sizer_6, 0, wx.EXPAND, 0)
        grid_sizer_2.Add(self.label_11, 0, wx.LEFT | wx.RIGHT | wx.TOP | wx.ALIGN_CENTER_VERTICAL, 15)
        grid_sizer_2.Add(self.emg2mouseGainBox, 0, wx.LEFT | wx.RIGHT | wx.TOP | wx.ALIGN_RIGHT | wx.ALIGN_CENTER_VERTICAL, 15)
        grid_sizer_2.Add(self.label_12, 0, wx.LEFT | wx.RIGHT | wx.TOP | wx.ALIGN_CENTER_VERTICAL, 15)
        grid_sizer_2.Add(self.emg2MouseSlopeBox, 0, wx.LEFT | wx.RIGHT | wx.TOP | wx.ALIGN_RIGHT | wx.ALIGN_CENTER_VERTICAL, 15)
        grid_sizer_2.Add(self.label_14, 0, wx.LEFT | wx.RIGHT | wx.TOP | wx.ALIGN_CENTER_VERTICAL, 15)
        grid_sizer_2.Add(self.emg2MouseOffsetBox, 0, wx.LEFT | wx.RIGHT | wx.TOP | wx.ALIGN_RIGHT | wx.ALIGN_CENTER_VERTICAL, 15)
        grid_sizer_2.Add(self.label_15, 0, wx.LEFT | wx.RIGHT | wx.TOP | wx.ALIGN_CENTER_VERTICAL, 15)
        grid_sizer_2.Add(self.mediansBox, 0, wx.LEFT | wx.RIGHT | wx.TOP | wx.ALIGN_RIGHT | wx.ALIGN_CENTER_VERTICAL, 15)
        grid_sizer_2.Add(self.label_16, 0, wx.LEFT | wx.RIGHT | wx.TOP | wx.ALIGN_CENTER_VERTICAL, 15)
        grid_sizer_2.Add(self.minSamplesBox, 0, wx.LEFT | wx.RIGHT | wx.TOP | wx.ALIGN_RIGHT | wx.ALIGN_CENTER_VERTICAL, 15)
        grid_sizer_2.Add(self.label_17, 0, wx.LEFT | wx.RIGHT | wx.TOP | wx.ALIGN_CENTER_VERTICAL, 15)
        grid_sizer_2.Add(self.sampleRateBox, 0, wx.LEFT | wx.RIGHT | wx.TOP | wx.ALIGN_RIGHT | wx.ALIGN_CENTER_VERTICAL, 15)
        self.notebook_1_pane_3.SetSizer(grid_sizer_2)
        grid_sizer_8.Add(self.label_28, 0, wx.LEFT | wx.RIGHT | wx.TOP | wx.ALIGN_CENTER_VERTICAL, 15)
        grid_sizer_8.Add(self.serialPortBox, 0, wx.LEFT | wx.RIGHT | wx.TOP | wx.ALIGN_RIGHT | wx.ALIGN_CENTER_VERTICAL, 15)
        grid_sizer_8.Add(self.label_29, 0, wx.LEFT | wx.RIGHT | wx.TOP | wx.ALIGN_CENTER_VERTICAL, 15)
        grid_sizer_8.Add(self.serialBaudBox, 0, wx.LEFT | wx.RIGHT | wx.TOP | wx.ALIGN_RIGHT | wx.ALIGN_CENTER_VERTICAL, 15)
        grid_sizer_8.Add(self.label_30, 0, wx.LEFT | wx.RIGHT | wx.TOP | wx.ALIGN_CENTER_VERTICAL, 15)
        grid_sizer_8.Add(self.serialDataBitsBox, 0, wx.LEFT | wx.RIGHT | wx.TOP | wx.ALIGN_RIGHT | wx.ALIGN_CENTER_VERTICAL, 15)
        grid_sizer_8.Add(self.label_31, 0, wx.LEFT | wx.RIGHT | wx.TOP | wx.ALIGN_CENTER_VERTICAL, 15)
        grid_sizer_8.Add(self.serialStopBitsBox, 0, wx.LEFT | wx.RIGHT | wx.TOP | wx.ALIGN_RIGHT | wx.ALIGN_CENTER_VERTICAL, 15)
        grid_sizer_8.Add(self.label_32, 0, wx.LEFT | wx.RIGHT | wx.TOP | wx.ALIGN_CENTER_VERTICAL, 15)
        grid_sizer_8.Add(self.combo_box_8, 0, wx.LEFT | wx.RIGHT | wx.TOP | wx.ALIGN_RIGHT | wx.ALIGN_CENTER_VERTICAL, 15)
        grid_sizer_8.Add(self.label_33, 0, wx.LEFT | wx.RIGHT | wx.TOP | wx.ALIGN_CENTER_VERTICAL, 15)
        sizer_7.Add(self.serialRTSCheck, 0, wx.RIGHT | wx.ALIGN_CENTER_VERTICAL, 15)
        sizer_7.Add(self.serialXonCheck, 0, wx.RIGHT | wx.ALIGN_RIGHT | wx.ALIGN_CENTER_VERTICAL, 15)
        grid_sizer_8.Add(sizer_7, 1, wx.ALIGN_RIGHT | wx.ALIGN_CENTER_VERTICAL, 0)
        grid_sizer_8.Add(self.panel_14, 1, wx.EXPAND, 0)
        grid_sizer_8.Add(self.panel_16, 1, wx.EXPAND, 0)
        grid_sizer_8.Add(self.panel_15, 1, wx.EXPAND, 0)
        grid_sizer_8.Add(self.panel_17, 1, wx.EXPAND, 0)
        self.serialParityBox.SetSizer(grid_sizer_8)
        self.notebook_1.AddPage(self.notebook_1_pane_1, "Player Information")
        self.notebook_1.AddPage(self.notebook_1_pane_2, "Internet/Server Settings")
        self.notebook_1.AddPage(self.notebook_1_pane_3, "EMG/Neurochip Settings")
        self.notebook_1.AddPage(self.serialParityBox, "Serial Settings")
        sizer_1.Add(self.notebook_1, 1, wx.EXPAND, 0)
        sizer_2.Add(self.button_1, 0, 0, 0)
        sizer_2.Add(self.button_2, 0, wx.LEFT, 10)
        sizer_1.Add(sizer_2, 0, wx.ALL | wx.ALIGN_RIGHT, 5)
        self.SetSizer(sizer_1)
        self.Layout()

# ~+-~+-~+-~+-~+-~+-~+-~+-~+-~+-~+-~+-~+-~+-~+-~+-~+-~+-~+-~+-~+-~+-~+-~+-~+-~+-~+-~+-~+-~
# ~+-~+-~+-~+-~+-~+-~+-~+-~+-~+-~+-~+-~+-~+-~+-~+-~+-~+-~+-~+-~+-~+-~+-~+-~+-~+-~+-~+-~+-~ 
    def Save(self): # save dialog contents
            f = file('ControlInterfaceConfig.pkl', 'w')
            pickle.dump(self.serverHost, f)
            pickle.dump(self.serverDir, f)
            pickle.dump(self.serverLogin, f)
            pickle.dump(self.password, f)
            pickle.dump(self.playername, f)
            pickle.dump(self.playerID, f)
            pickle.dump(self.playerhandle, f)
            pickle.dump(self.playerside, f)
            pickle.dump(self.playerflexor, f)
            pickle.dump(self.playerextensor, f)
            pickle.dump(self.changain,f)
            #pickle.dump(self.changain2,f)
            pickle.dump(self.chanoffset,f)
            #pickle.dump(self.chanoffset2,f)
            pickle.dump(self.gainEMG,f)
            pickle.dump(self.slopeEMG,f)
            pickle.dump(self.EMGxoffset,f)
            pickle.dump(self.smoothernummeds,f)
            pickle.dump(self.EMGnumSamples,f)
            pickle.dump(self.serialSampleRate,f)
            success = True

# ~+-~+-~+-~+-~+-~+-~+-~+-~+-~+-~+-~+-~+-~+-~+-~+-~+-~+-~+-~+-~+-~+-~+-~+-~+-~+-~+-~+-~+-~
# ~+-~+-~+-~+-~+-~+-~+-~+-~+-~+-~+-~+-~+-~+-~+-~+-~+-~+-~+-~+-~+-~+-~+-~+-~+-~+-~+-~+-~+-~
    def OnOK(self, event): 
        self.serverHost = self.serverAddressBox.GetValue()
        self.serverDir = self.serverDirectoryBox.GetValue()
        self.serverLogin = self.serverserverLoginBox.GetValue()
        self.password = self.serverPasskeyBox.GetValue()
        self.playername = self.playerNameBox.GetValue()
        self.playerID = self.playerIDBox.GetValue()
        self.playerhandle = self.playerHandleBox.GetValue()
        self.playerside = self.playerHandBox.GetValue()
        self.playerflexor = self.playerFlexorBox.GetValue()
        self.playerextensor = self.playerExtensorBox.GetValue()
        self.changain[0] = float(self.ch1GainBox.GetValue())
        self.changain[1] = float(self.ch2GainBox.GetValue())
        self.chanoffset[0] = float(self.ch1OffsetBox.GetValue())
        self.chanoffset[1] = float(self.ch2OffsetBox.GetValue())
        self.gainEMG = float(self.emg2mouseGainBox.GetValue())
        self.slopeEMG = float(self.emg2MouseSlopeBox.GetValue())
        self.EMGxoffset = float(self.emg2MouseOffsetBox.GetValue())
        self.smoothernummeds = float(self.mediansBox.GetValue())
        self.EMGnumSamples = float(self.minSamplesBox.GetValue())
        self.serialSampleRate = float(self.sampleRateBox.GetValue())
        self.Save()
        self.EndModal(wx.ID_OK)

# ~+-~+-~+-~+-~+-~+-~+-~+-~+-~+-~+-~+-~+-~+-~+-~+-~+-~+-~+-~+-~+-~+-~+-~+-~+-~+-~+-~+-~+-~
# ~+-~+-~+-~+-~+-~+-~+-~+-~+-~+-~+-~+-~+-~+-~+-~+-~+-~+-~+-~+-~+-~+-~+-~+-~+-~+-~+-~+-~+-~ 
    def OnCancel(self, event): 
        self.EndModal(wx.ID_CANCEL)

# ~+-~+-~+-~+-~+-~+-~+-~+-~+-~+-~+-~+-~+-~+-~+-~+-~+-~+-~+-~+-~+-~+-~+-~+-~+-~+-~+-~+-~+-~
# ~+-~+-~+-~+-~+-~+-~+-~+-~+-~+-~+-~+-~+-~+-~+-~+-~+-~+-~+-~+-~+-~+-~+-~+-~+-~+-~+-~+-~+-~ 
    def DefineVariables(self): 
        self.serverAddressBox.SetValue(self.serverHost)
        self.serverDirectoryBox.SetValue(self.serverDir)
        self.serverserverLoginBox.SetValue(self.serverLogin)
        self.serverPasskeyBox.SetValue(self.password)

        self.playerNameBox.SetValue(self.playername)
        self.playerIDBox.SetValue(self.playerID)
        self.playerHandleBox.SetValue(self.playerhandle)
        self.playerHandBox.SetValue(self.playerside)
        self.playerFlexorBox.SetValue(self.playerflexor)
        self.playerExtensorBox.SetValue(self.playerextensor)

        self.ch1GainBox.SetValue(str(self.changain[0]))
        self.ch2GainBox.SetValue(str(self.changain[1]))
        self.ch1OffsetBox.SetValue(str(self.chanoffset[0]))
        self.ch2OffsetBox.SetValue(str(self.chanoffset[1]))
        self.emg2mouseGainBox.SetValue(str(self.gainEMG))
        self.emg2MouseSlopeBox.SetValue(str(self.slopeEMG))
        self.emg2MouseOffsetBox.SetValue(str(self.EMGxoffset))
        self.mediansBox.SetValue(str(self.smoothernummeds))
        self.minSamplesBox.SetValue(str(self.EMGnumSamples))
        self.sampleRateBox.SetValue(str(self.serialSampleRate))

# ~+-~+-~+-~+-~+-~+-~+-~+-~+-~+-~+-~+-~+-~+-~+-~+-~+-~+-~+-~+-~+-~+-~+-~+-~+-~+-~+-~+-~+-~
# ~+-~+-~+-~+-~+-~+-~+-~+-~+-~+-~+-~+-~+-~+-~+-~+-~+-~+-~+-~+-~+-~+-~+-~+-~+-~+-~+-~+-~+-~ 
    def Load(self): # save dialog contents
        if not os.path.exists("ControlInterfaceConfig.pkl"):
            self.Save()
        else:
            f = file('ControlInterfaceConfig.pkl', 'r')
            self.serverHost = pickle.load(f)
            self.serverDir = pickle.load(f)
            self.serverLogin = pickle.load(f)
            self.password = pickle.load(f)
            self.playername = pickle.load(f)
            self.playerID = pickle.load(f)
            self.playerhandle = pickle.load(f)
            self.playerside = pickle.load(f)
            self.playerflexor = pickle.load(f)
            self.playerextensor = pickle.load(f)
            self.changain = pickle.load(f)
            #self.changain2 = pickle.load(f)
            self.chanoffset = pickle.load(f)
            #self.chanoffset2 = pickle.load(f)
            self.gainEMG = pickle.load(f)
            self.slopeEMG = pickle.load(f)
            self.EMGxoffset = pickle.load(f)
            self.smoothernummeds = pickle.load(f)
            self.EMGnumSamples = pickle.load(f)
            self.serialSampleRate = pickle.load(f)
            self.DefineVariables()
            success = True

# ~+-~+-~+-~+-~+-~+-~+-~+-~+-~+-~+-~+-~+-~+-~+-~+-~+-~+-~+-~+-~+-~+-~+-~+-~+-~+-~+-~+-~+-~
# ~+-~+-~+-~+-~+-~+-~+-~+-~+-~+-~+-~+-~+-~+-~+-~+-~+-~+-~+-~+-~+-~+-~+-~+-~+-~+-~+-~+-~+-~
if __name__ == "__main__":
    app = wx.PySimpleApp(0)
    wx.InitAllImageHandlers()
    dialog_1 = MyDialog(None, -1, "")
    app.SetTopWindow(dialog_1)
    dialog_1.Show()
    app.MainLoop()
